<?php
class AccessDB
{
    private $db;
    private $table;
    
    /**
     * Open the database using default login and password.
     */
    public function __construct()
    {
        $username = "root";
        $password = "";
        $database = "db1";
        $this->table = "guestbook";
        
        // Open the database
        $this->db = mysqli_connect("localhost", $username, $password);        
        if ($this->db == false) {
            die("Unable to connect to database");
        } 
        
        // Select database
        mysqli_select_db($this->db, $database);
    }
    
    /**
     * Closes the database.
     */
    public function __destruct()
    {
        mysqli_close($this->db);
    }
    
    /**
     * Return in an table (two-dimensional array) all entries of the guest book.
     * Each row of the table represents one entry in the guest book.
     * @return table[...]["Index"]   --> Integer: Index of the entry (for deleting)
     *         table[...]["Name"]    --> String: name of the user
     *         table[...]["eMail"]   --> String: e-Mail of the user
     *         table[...]["veloType"] --> String: The guest book entry (as text)
     *         table[...]["Date"]    --> String: Date and time of the entry
     */
    public function getEntries()
    {
        // Make querry
        $t = $this->table;
        $result = mysqli_query($this->db, "SELECT * FROM $t");
        
        $table = false;
        $i = 0;
        while ($row = mysqli_fetch_array($result)) {
            $table[$i]["Index"]   = $row["indes"];
            $table[$i]["Date"]    = $row["cur_date"];
            $table[$i]["Name"]    = $row["namep"];
          //  $table[$i]["eMail"]   = $row["email"]; // not displaying email in public
            $table[$i]["veloType"] = $row["veloType"];
            $i++;
        }
        
        mysqli_free_result($result);
        
        return $table;
    }
    
    /**
     * 
     * @param String $name    User name
     * @param String $eMail   User e-mail address
     * @param String $veloType The bike which the user has selected
     * @return On success: Integer Index generated by the database for the entry
     *         On failure: Boolean false
     */
    function addEntry($name, $eMail, $veloType)
    {   
        
        function debugthis($data) {
            $output = $data;
            if (is_array($output))
                $output = implode(',', $output);
        
             echo "<script>console.log('text " . $output . "' );</script>";
        }
        
        // For security: supress SQL injection
        $name    = mysqli_real_escape_string($this->db, $name);
        $eMail   = mysqli_real_escape_string($this->db, $eMail);
        $veloType = mysqli_real_escape_string($this->db, $veloType);
        

        // Add entry to the database
        $t = $this->table; // local variable, because I could not use "$this->table" in the subsequent line
        $result = mysqli_query($this->db, "INSERT INTO $t (namep, email, veloType) VALUES ('$name', '$eMail', '$veloType')");
        
        

        if ($result)
        {
            $result = mysqli_insert_id($this->db);
        } else {
           debug("Failed to add entry.");
        }

        return $result;
    }
    
    /**
     * Return one-dimensional array of all data of one entry
     * @return list["Index"]   --> Integer: Index of the entry (for deleting)
     *         list["Name"]    --> String: name of the user
     *         list["eMail"]   --> String: e-Mail of the user
     *         list["Comment"] --> String: The guest book entry (as text)
     *         list["Date"]    --> String: Date and time of the entry
     */
    public function getEntry($index)
    {
        // For security: supress SQL injection
        settype($index, 'Integer');

        // Make query
        $t = $this->table;
        $result = mysqli_query($this->db, "SELECT * FROM $t WHERE indes = '$index'");
        
        $list = false;
        $row = mysqli_fetch_array($result);
        if ($row != false) {            
            $list["Index"]   = $row["indes"];
            $list["Date"]    = $row["cur_date"];
            $list["Name"]    = $row["namep"];
            $list["eMail"]   = $row["email"];
            $list["veloType"] = $row["veloType"];
        }
        
        mysqli_free_result($result);
        
        return $list;
    }
        
    /**
     * Removes the entry with the given index from the database.
     * @param Integer $index Index of the entry to remove
     * @return Boolean true on success.
     */
    function removeEntry($index)
    {
        // For security: supress SQL injection
        settype($index, 'Integer');
        $t = $this->table;
        $result = mysqli_query($this->db, "DELETE FROM $t WHERE indes = '$index'");
        
        return $result;
    }
   
}
?>